### ISSUE TITLE
open/close Halo command/property

### ISSUE THREAD

**Issue by dkrasner** [dkrasner/Simpletalk#76]
### Main points ###
When writing our "parts" documentation stack I found that in a number of instances it would be good to be able to open/close the halo programmatically or have a part that referred to have the halo open. 

The ST way to do this would be to have a `halo-open` true/false property and corresponding `openHalo` `closeHalo` messages  instead of the current method and attribute on the `PartView` subclass setup.

**Comment by darth-cheney** [comment]
Yes this is a good idea.
  
One thing to watch out for is the single model / multiple view setup we have now (ie, with the Navigator and lensed views). The `halo-open` property should be a read-only (except when set by primitive commands), dynamic prop. It should return true if _any_ view that has the Part's id also has a Halo open and false otherwise.
  
I also think we should keep the API (`openHalo` / `closeHalo`) on the PartView side and just have the message handling call them whenever the property has changed. No sense in getting rid of them there.

**Comment by dkrasner** [comment]
> I also think we should keep the API (`openHalo` / `closeHalo`) on the PartView side and just have the message handling call them whenever the property has changed. No sense in getting rid of them there.

exactly what i was thinking

**Comment by dkrasner** [comment]
similarly with open and close the nav
